new Vue({
	el:'body',
	data:function  () {
		return{
			//table切换
			table:{
				itr:{show:true},
				list:{show:false},
				talk:{show:false}
			},
			//文章列表数据
			//章节目录自定义
			chinaword:['一','二','三','四','五','六','七','八','九','十','十一','十二','十三','十四','十五','十六','十七','十八','十九','二十'],
			courselist:[
			  {
			  	title:'指尖上的传承之玉雕',
			  	children:[
			  	{
			  		title:'中国玉文化概述',
			  		time:'00:20:35'
			  	},
			  	{
			  		title:'中国玉文化概述',
			  		time:'00:20:35'
			  	},
			  	{
			  		title:'中国玉文化概述',
			  		time:'00:20:35'
			  	},
			  	]
			  },
			  {
			  	title:'指尖上的传承之玉雕',
			  	children:[
			  	{
			  		title:'中国玉文化概述',
			  		time:'00:20:35'
			  	},
			  	{
			  		title:'中国玉文化概述',
			  		time:'00:20:35'
			  	},
			  	{
			  		title:'中国玉文化概述',
			  		time:'00:20:35'
			  	},
			  	]
			  },
			  {
			  	title:'指尖上的传承之玉雕',
			  	children:[
			  	{
			  		title:'中国玉文化概述',
			  		time:'00:20:35'
			  	},
			  	{
			  		title:'中国玉文化概述',
			  		time:'00:20:35'
			  	},
			  	{
			  		title:'中国玉文化概述',
			  		time:'00:20:35'
			  	},
			  	]
			  },
			  
			]
		}
	},
	//方法区
	methods:{
		tablecheck:function  (item) {
			if (item.show) {
				return false;
			}else{
				this.table.itr.show=false;
				this.table.list.show=false;
				this.table.talk.show=false;
				item.show=true;
			}
		}
	}
})